## Контрольная работа

In [1]:
import pandas as pd
import numpy as np

### Датафрейм с которым вы будете сегодня работать

In [9]:
data = [['Girev', 'Andrey', 'ВИП', 2815, 29, 58, 6358, 'Moscow', 'Xiaomi'],
       ['Bykin', 'Stas', 'Все за 300', 3634, 37, 78, 602, 'Kazan',
        'Samsung'],
       ['Ivanov', 'Alex', 'Всё за 800', 410, 47, 81, 3582, 'Moscow',
        'Huawei'],
       ['Andreev', 'Sergey', 'Всё за 500', 1981, 75, 98, 5442, 'Kazan',
        'Apple'],
       ['Girev', 'Stas', 'Всё за 800', 4969, 43, 61, 8510, 'Moscow',
        'Samsung'],
       ['Bykin', 'Andrey', 'Всё за 500', 4308, 49, 39, 2525, 'Moscow',
        'Xiaomi'],
       ['Kozlov', 'Igor', 'Всё за 800', 300, 60, 31, 8543, 'Yakutsk',
        'Samsung'],
       ['Girev', 'Alex', 'Промо', 4199, 47, 90, 3925, 'Kazan', 'Apple'],
       ['Petrov', 'Nikolay', 'ВИП', 4810, 72, 88, 7188, 'Moscow',
        'Apple'],
       ['Andreev', 'Sergey', 'Всё за 800', 4118, 52, 53, 419, 'Yakutsk',
        'Apple'],
       ['Smolov', 'Stas', 'Промо', 1991, 28, 67, 5016, 'Kazan', 'Xiaomi'],
       ['Girev', 'Igor', 'Корпоративный', 1430, 69, 19, 9520, 'Yakutsk',
        'Samsung'],
       ['Kozlov', 'Andrey', 'Корпоративный', 113, 71, 82, 2785, 'Kazan',
        'Apple'],
       ['Ivanov', 'Sergey', 'Промо', 3394, 39, 12, 2718, 'Yakutsk',
        'Xiaomi'],
       ['Smolov', 'Sergey', 'Всё за 250 (архив)', 3493, 32, 6, 8959,
        'Yakutsk', 'Huawei'],
       ['Kozlov', 'Stas', 'Всё за 800', 4565, 59, 82, 3168, 'Moscow',
        'Apple'],
       ['Vlasov', 'Andrey', 'Всё за 800', 3192, 29, 74, 2852, 'Yakutsk',
        'Xiaomi'],
       ['Smolov', 'Alex', 'Корпоративный', 3764, 71, 22, 2768, 'Moscow',
        'Huawei'],
       ['Vlasov', 'Sergey', 'Всё за 800', 3816, 28, 35, 5734,
        'Vladivostok', 'Apple'],
       ['Bykin', 'Alex', 'Промо', 817, 65, 34, 2131, 'Vladivostok',
        'Samsung'],
       ['Andreev', 'Nikolay', 'Всё за 500', 385, 49, 62, 1815, 'Kazan',
        'Xiaomi'],
       ['Bykin', 'Igor', 'Всё за 500', 2642, 38, 11, 3787, 'Moscow',
        'Xiaomi'],
       ['Girev', 'Sergey', 'Все за 300', 4230, 62, 68, 5512,
        'Vladivostok', 'Samsung'],
       ['Bykin', 'Sergey', 'Всё за 800', 4100, 48, 39, 227, 'Moscow',
        'Xiaomi'],
       ['Girev', 'Stas', 'Все за 300', 3371, 53, 24, 7946, 'Kazan',
        'Apple'],
       ['Smolov', 'Sergey', 'Корпоративный', 3577, 70, 71, 8847,
        'Yakutsk', 'Huawei'],
       ['Mezov', 'Nikolay', 'Всё за 250 (архив)', 2742, 28, 19, 7115,
        'Yakutsk', 'Huawei'],
       ['Smolov', 'Stas', 'Всё за 500', 2644, 41, 33, 8341, 'Moscow',
        'Xiaomi'],
       ['Vlasov', 'Andrey', 'Всё за 500', 4725, 26, 93, 9441,
        'Vladivostok', 'Xiaomi'],
       ['Ivanov', 'Nikolay', 'Всё за 500', 2785, 41, 5, 2901, 'Moscow',
        'Samsung']]

df = pd.DataFrame(data, columns = ['surname', 'name', 'tarif', 'balance', 'age', 'sms', 
                                   'voice', 'city', 'phone'])

In [42]:
df

,surname,name,tarif,balance,age,sms,voice,city,phone
0,Girev,Andrey,ВИП,2815,29,58,6358,Moscow,Xiaomi
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung
2,Ivanov,Alex,Всё за 800,410,47,81,3582,Moscow,Huawei
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple
8,Petrov,Nikolay,ВИП,4810,72,88,7188,Moscow,Apple
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung

In [1]:
#surname    - Фамилия клиента 
#name       - Имя клиента
#tarif      - Тариф клиента
#balance	- Баланс клиента
#age	    - Возраст клиента
#sms	    - Количество отправленных СМС
#voice	    - Количество секунд разговора (звонки)
#city	    - Город клиента
#phone      - Марка телефона клиента

## Ответы на вопросы загрузите на степик

### Вопрос 1: определите средний возраст клиента

In [3]:
df['age'].mean()

48.6

### Вопрос 2: на каком тарифе средний возраст клиента наименьший

In [16]:
df.groupby('tarif').age.mean().idxmin()

'Всё за 250 (архив)'

### Вопрос 3: с какого города больше всего клиентов?

In [44]:
df.city.value_counts().idxmax()

'Moscow'

### Вопрос 4: на каком тарифе отправили больше всего СМС?

In [46]:
df.groupby('tarif').sms.sum().idxmax()

'Всё за 800'

### Вопрос 5: определите самую популярную марку смартфона у пользователей до 40 (включительно)

In [64]:
#Отсеиваю лишних клиентов, чтобы было проще работать
df2 = df[df['age'] <= 40]
df2

,surname,name,tarif,balance,age,sms,voice,city,phone
0,Girev,Andrey,ВИП,2815,29,58,6358,Moscow,Xiaomi
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi

In [72]:
#Можно было не считать :D
df2.groupby('phone').phone.count().sort_values(ascending=False)

phone
Xiaomi     6
Huawei     2
Apple      1
Samsung    1
Name: phone, dtype: int64

### Вопрос 6: определите самую популярную марку смартфона у пользователей старше 40

In [73]:
#Предыдущая задача наоборот
#Отсеиваю лишних клиентов, чтобы было проще работать
df2 = df[df['age'] >= 40]
df2

,surname,name,tarif,balance,age,sms,voice,city,phone
2,Ivanov,Alex,Всё за 800,410,47,81,3582,Moscow,Huawei
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple
8,Petrov,Nikolay,ВИП,4810,72,88,7188,Moscow,Apple
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung

In [75]:
#Так же можно было не считать
df2.groupby('phone').phone.count().sort_values(ascending=False)

phone
Apple      7
Samsung    6
Xiaomi     4
Huawei     3
Name: phone, dtype: int64

### Вопрос 7: В каком городе клиенты меньше всего отправляют СМС

In [80]:
df.groupby('city').sms.sum().idxmin()

'Vladivostok'

### Вопрос 8: В каком городе клиенты больше всего говорят по телефону?

In [84]:
df.groupby('city').voice.sum().idxmax()

'Moscow'

### Вопрос 9: Сколько заработала фирма на СМС сообщениях? Стоимость одного сообщения 3 рубля.

In [86]:
df.sms.sum()*3

4605

### Вопрос 10: Сколько заработала фирма на СМС сообщениях? Тарифная сетка:
#### ВИП                   - 1 рубль за СМС
####  Все за 300            - 2 рубля за СМС
####  Всё за 500            - 3 рубля за СМС
####  Всё за 800            - 4 рубля за СМС
####  Промо                 - 7 рублей за СМС
####  Корпоративный         - 0 рублей за СМС
####  Всё за 250 (архив)    - 5 рублей за СМС

In [227]:
#Создаю DF сгруппированный по тарифам и транспонированый для перемножения с серией
df3 = df.groupby('tarif').sum().T
df3

tarif,ВИП,Все за 300,Всё за 250 (архив),Всё за 500,Всё за 800,Корпоративный,Промо
balance,7625,11235,6235,19470,25470,8884,10401
age,101,152,60,319,366,281,179
sms,146,170,25,341,456,194,203
voice,13546,14060,16074,34252,33035,23920,13790

In [270]:
#Создаю дата фрэйм именно с СМС и нужными индексами для перемножения с серией тарифов
df4 = df3.loc['sms']
df4.index

Index(['ВИП', 'Все за 300', 'Всё за 250 (архив)', 'Всё за 500', 'Всё за 800',
       'Корпоративный', 'Промо'],
      dtype='object', name='tarif')

In [269]:
#Создаю серию с нужными индексами
price = pd.Series({'ВИП': 1, 
         'Все за 300': 2, 
         'Всё за 500': 3, 
         'Всё за 800': 4, 
         'Промо': 7, 
         'Корпоративный': 0, 
         'Всё за 250 (архив)': 5})
price.index

Index(['ВИП', 'Все за 300', 'Всё за 500', 'Всё за 800', 'Промо',
       'Корпоративный', 'Всё за 250 (архив)'],
      dtype='object')

In [265]:
#перемножаю df и серию. Получаю сумму
(df4 * price).sum()

4879

- Вот побольше бы таких задача с DF. Для того. чтобы реально отточить навыки
- Несколько решений из ответов других учащихся

In [272]:
(df.groupby('tarif').sum().sms * [1, 2, 5, 3, 4, 0, 7]).sum()

4879

In [271]:
sms_price = pd.Series([1,2,3,4,7,0,5], index=["ВИП", "Все за 300", "Всё за 500", "Всё за 800", "Промо", "Корпоративный", "Всё за 250 (архив)"])
(df.groupby("tarif")["sms"].sum() * sms_price).sum()

4879

### Вопрос 11: Определите процент клиентов, у которых баланс выше 4000

In [146]:
#Отбираю клиентов, у кого баланс больше 4000
df.loc[df['balance'] > 4000]

,surname,name,tarif,balance,age,sms,voice,city,phone
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple
8,Petrov,Nikolay,ВИП,4810,72,88,7188,Moscow,Apple
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi

In [164]:
#подсчитываю количество таких клиентов
len(df.loc[df['balance'] > 4000])

9

In [166]:
#Получаю % такиз пользователей
len(df.loc[df['balance'] > 4000]) / len(df) * 100

30.0

### Вопрос 12: Определите процент клиентов, у которых баланс выше 2000 и тариф 'Всё за 500'

In [177]:
#Отбираем клиентов, соответствующих запросу
шейхи = df.loc[(df['balance'] > 2000) & (df['tarif'] == 'Всё за 500')]
шейхи

,surname,name,tarif,balance,age,sms,voice,city,phone
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung

In [182]:
#Определяем их %
np.floor(len(шейхи) / len(df) * 100)

16.0

### Вопрос 13: Сколько клиентов из Москвы, у которых баланс выше 1500 и марка телефона 'Apple'?

In [189]:
#Отбираем данных клиентов
len(df.loc[(df['city'] == 'Moscow') & (df['balance'] > 1500) & (df['phone'] == 'Apple')])

2

### Вопрос 14: Самое распространённое имя среди наших клиентов?

In [196]:
#В голову пришла сразу группировка по имени и подсчет максимального кол-ва фамилий idxmax()
df.groupby('name').surname.count().idxmax()

'Sergey'

In [197]:
#Естественно есть еще и "мода". Получение наиболее частовстречающегося значения
#Но на данном этапе курсы данная функция не изучалась
(df["name"]).mode()

0    Sergey
Name: name, dtype: object

### Вопрос 15: Определите процент клиентов у которых телефон Apple и они из Владивостока

In [203]:
#Аналогично прошлых задач
np.floor(len(df[(df['phone']=='Apple') & (df['city'] == 'Vladivostok')]) / len(df)*100)

3.0

# Контрольная работа, часть 2
## Продолжение контрольной работы. Датафрейм тот же самый, только теперь будем вносить в него изменения. Если вам удобно - решайте в ноутбуке, а итог переносите в степик.
Решайте не спеша, пропускайте сложное, начинайте с того, что уже хорошо получается.

### Задача 1
Объедините столбцы surname и name в столбец с именем client_name

![Картинка испарилась(((](https://ucarecdn.com/4e804078-9c92-49a2-9525-3c19ed828062/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [6]:
df['client_name'] = df['surname'] +' '+ df['name']
df

,surname,name,tarif,balance,age,sms,voice,city,phone,client_name
0,Girev,Andrey,ВИП,2815,29,58,6358,Moscow,Xiaomi,Girev Andrey
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,Bykin Stas
2,Ivanov,Alex,Всё за 800,410,47,81,3582,Moscow,Huawei,Ivanov Alex
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple,Andreev Sergey
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung,Girev Stas
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi,Bykin Andrey
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung,Kozlov Igor
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple,Girev Alex
8,Petrov,Nikolay,ВИП,4810,72,88,7188,Moscow,Apple,Petrov Nikolay
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple,Andreev Sergey
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi,Smolov Stas
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung,Girev Igor
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple,Kozlov Andrey
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi,Ivanov Sergey
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei,Smolov Sergey
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple,Kozlov Stas
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi,Vlasov Andrey
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei,Smolov Alex
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple,Vlasov Sergey
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung,Bykin Alex
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi,Andreev Nikolay
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi,Bykin Igor
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung,Girev Sergey
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi,Bykin Sergey
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple,Girev Stas
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei,Smolov Sergey
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei,Mezov Nikolay
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi,Smolov Stas
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi,Vlasov Andrey
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung,Ivanov Nikolay

### Задача 2
Поступила задача разбить клиентов на группы:

до 25 лет (включительно) - A (англ. буква)

с 26 до 40 лет (включительно) - B (англ. буква)

старше 40 лет - C (англ. буква)

Запишите название группы в столбец group:
![Картинка испарилась(((](https://ucarecdn.com/b3578aa4-9daf-471c-9b3b-817b24399b65/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [12]:
df['group'] = np.where(df['age'] <= 25, 'A', 
                       np.where(df['age'] > 40, 'C', 'B'))
df

,surname,name,tarif,balance,age,sms,voice,city,phone,client_name,group
0,Girev,Andrey,ВИП,2815,29,58,6358,Moscow,Xiaomi,Girev Andrey,B
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,Bykin Stas,B
2,Ivanov,Alex,Всё за 800,410,47,81,3582,Moscow,Huawei,Ivanov Alex,C
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple,Andreev Sergey,C
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung,Girev Stas,C
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi,Bykin Andrey,C
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung,Kozlov Igor,C
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple,Girev Alex,C
8,Petrov,Nikolay,ВИП,4810,72,88,7188,Moscow,Apple,Petrov Nikolay,C
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple,Andreev Sergey,C
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi,Smolov Stas,B
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung,Girev Igor,C
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple,Kozlov Andrey,C
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi,Ivanov Sergey,B
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei,Smolov Sergey,B
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple,Kozlov Stas,C
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi,Vlasov Andrey,B
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei,Smolov Alex,C
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple,Vlasov Sergey,B
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung,Bykin Alex,C
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi,Andreev Nikolay,C
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi,Bykin Igor,B
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung,Girev Sergey,C
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi,Bykin Sergey,C
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple,Girev Stas,C
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei,Smolov Sergey,C
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei,Mezov Nikolay,B
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi,Smolov Stas,C
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi,Vlasov Andrey,B
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung,Ivanov Nikolay,C

### Задача 3
Пришла информация, что на сервере в Москве возник сбой и баланс за отправленные смс не списался (у пользователей из Москвы). Спишите с каждого пользователя из Москвы деньги за смс. Количество отправленных смс за которые не списали деньги в столбце sms. Стоимость 1 смс - 3 рубля. (обновите колонку balance):
![Картинка испарилась(((](https://ucarecdn.com/0452fc5c-5f0f-41db-97f6-221644e17f20/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [71]:
#Решение с помощью Numpy
df['balance'] = np.where(df['city'] == 'Moscow', df['balance'] - df['sms'] * 3, df['balance'])
df

,surname,name,tarif,balance,age,sms,voice,city,phone
0,Girev,Andrey,ВИП,2641,29,58,6358,Moscow,Xiaomi
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung
2,Ivanov,Alex,Всё за 800,167,47,81,3582,Moscow,Huawei
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple
4,Girev,Stas,Всё за 800,4786,43,61,8510,Moscow,Samsung
5,Bykin,Andrey,Всё за 500,4191,49,39,2525,Moscow,Xiaomi
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple
8,Petrov,Nikolay,ВИП,4546,72,88,7188,Moscow,Apple
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei
15,Kozlov,Stas,Всё за 800,4319,59,82,3168,Moscow,Apple
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi
17,Smolov,Alex,Корпоративный,3698,71,22,2768,Moscow,Huawei
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi
21,Bykin,Igor,Всё за 500,2609,38,11,3787,Moscow,Xiaomi
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung
23,Bykin,Sergey,Всё за 800,3983,48,39,227,Moscow,Xiaomi
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei
27,Smolov,Stas,Всё за 500,2545,41,33,8341,Moscow,Xiaomi
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi
29,Ivanov,Nikolay,Всё за 500,2770,41,5,2901,Moscow,Samsung

In [74]:
#Решение с помощью Pandas
df.balance[df.city == 'Moscow'] -= df.sms*3
df

C:\Users\user\AppData\Local\Temp\ipykernel_13676\1071810829.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.balance[df.city == 'Moscow'] -= df.sms*3

,surname,name,tarif,balance,age,sms,voice,city,phone
0,Girev,Andrey,ВИП,2641,29,58,6358,Moscow,Xiaomi
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung
2,Ivanov,Alex,Всё за 800,167,47,81,3582,Moscow,Huawei
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple
4,Girev,Stas,Всё за 800,4786,43,61,8510,Moscow,Samsung
5,Bykin,Andrey,Всё за 500,4191,49,39,2525,Moscow,Xiaomi
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple
8,Petrov,Nikolay,ВИП,4546,72,88,7188,Moscow,Apple
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei
15,Kozlov,Stas,Всё за 800,4319,59,82,3168,Moscow,Apple
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi
17,Smolov,Alex,Корпоративный,3698,71,22,2768,Moscow,Huawei
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi
21,Bykin,Igor,Всё за 500,2609,38,11,3787,Moscow,Xiaomi
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung
23,Bykin,Sergey,Всё за 800,3983,48,39,227,Moscow,Xiaomi
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei
27,Smolov,Stas,Всё за 500,2545,41,33,8341,Moscow,Xiaomi
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi
29,Ivanov,Nikolay,Всё за 500,2770,41,5,2901,Moscow,Samsung

In [76]:
df.loc[df['city'] == 'Moscow', ['balance']]=df['balance'] - df['sms'] * 3
df

,surname,name,tarif,balance,age,sms,voice,city,phone
0,Girev,Andrey,ВИП,2641,29,58,6358,Moscow,Xiaomi
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung
2,Ivanov,Alex,Всё за 800,167,47,81,3582,Moscow,Huawei
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple
4,Girev,Stas,Всё за 800,4786,43,61,8510,Moscow,Samsung
5,Bykin,Andrey,Всё за 500,4191,49,39,2525,Moscow,Xiaomi
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple
8,Petrov,Nikolay,ВИП,4546,72,88,7188,Moscow,Apple
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei
15,Kozlov,Stas,Всё за 800,4319,59,82,3168,Moscow,Apple
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi
17,Smolov,Alex,Корпоративный,3698,71,22,2768,Moscow,Huawei
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi
21,Bykin,Igor,Всё за 500,2609,38,11,3787,Moscow,Xiaomi
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung
23,Bykin,Sergey,Всё за 800,3983,48,39,227,Moscow,Xiaomi
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei
27,Smolov,Stas,Всё за 500,2545,41,33,8341,Moscow,Xiaomi
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi
29,Ivanov,Nikolay,Всё за 500,2770,41,5,2901,Moscow,Samsung

### Задача 4
На совещании было принято решение детальнее проработать вопрос списания денежных средств. Теперь, спишите деньги (у пользователей из Москвы за смс) с учетом тарифной сетки:

ВИП - 1 рубль за СМС

Все за 300 - 2 рубля за СМС

Всё за 500 - 3 рубля за СМС

Всё за 800 - 4 рубля за СМС

Промо - 7 рублей за СМС

Корпоративный - 0 рублей за СМС

Всё за 250 (архив) - 5 рублей за СМС

![Картинка испарилась(((](https://ucarecdn.com/84dd4e5a-64e5-4f3e-9a23-d6de473f313d/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [3]:
d = {'ВИП': 1,  
     'Все за 300': 2, 
     'Всё за 500': 3,  
     'Всё за 800': 4, 
     'Промо': 7, 
     'Корпоративный': 0, 
     'Всё за 250 (архив)': 5}
d

{'ВИП': 1,
 'Все за 300': 2,
 'Всё за 500': 3,
 'Всё за 800': 4,
 'Промо': 7,
 'Корпоративный': 0,
 'Всё за 250 (архив)': 5}

In [10]:
df['sms_price'] = df['tarif'].map(d)
df.loc[df['city'] == 'Moscow', ['balance']]=df['balance'] - df['sms'] * df['sms_price']
df = df.drop(['sms_price'], axis = 1)
df

,surname,name,tarif,balance,age,sms,voice,city,phone
0,Girev,Andrey,ВИП,2757,29,58,6358,Moscow,Xiaomi
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung
2,Ivanov,Alex,Всё за 800,86,47,81,3582,Moscow,Huawei
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple
4,Girev,Stas,Всё за 800,4725,43,61,8510,Moscow,Samsung
5,Bykin,Andrey,Всё за 500,4191,49,39,2525,Moscow,Xiaomi
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple
8,Petrov,Nikolay,ВИП,4722,72,88,7188,Moscow,Apple
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei
15,Kozlov,Stas,Всё за 800,4237,59,82,3168,Moscow,Apple
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi
21,Bykin,Igor,Всё за 500,2609,38,11,3787,Moscow,Xiaomi
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung
23,Bykin,Sergey,Всё за 800,3944,48,39,227,Moscow,Xiaomi
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei
27,Smolov,Stas,Всё за 500,2545,41,33,8341,Moscow,Xiaomi
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi
29,Ivanov,Nikolay,Всё за 500,2770,41,5,2901,Moscow,Samsung

In [ ]:
#РЕШЕНИЕ
import pandas as pd
import  numpy as np

d = {'ВИП': 1,  
     'Все за 300': 2, 
     'Всё за 500': 3,  
     'Всё за 800': 4, 
     'Промо': 7, 
     'Корпоративный': 0, 
     'Всё за 250 (архив)': 5}
    
def solution(df):
    
    df['sms_price'] = df['tarif'].map(d)
    df.loc[df['city'] == 'Moscow', ['balance']]=df['balance'] - df['sms'] * df['sms_price']
    df = df.drop(['sms_price'], axis = 1)
    
    return df

### Задача 5
Пользователь Girev Sergey написал заявление о том, что переехал из города Vladivostok в Kazan. Внесите изменения в датафрейм:
![Картинка испарилась(((](https://ucarecdn.com/fb6304b5-ec17-4604-bbfd-afc709f54f88/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [107]:
df5 = df

In [129]:
df5.loc[(df5['name'] == 'Sergey') & (df5['surname'] == 'Girev') & (df5.city == 'Vladivostok'), 
        'city'] = 'Kazan'

In [130]:
df5

,surname,name,tarif,balance,age,sms,voice,city,phone,sms_price
0,Girev,Andrey,ВИП,2815,29,58,6358,Moscow,Xiaomi,NaN
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,NaN
2,Ivanov,Alex,Всё за 800,410,47,81,3582,Moscow,Huawei,NaN
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple,NaN
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung,NaN
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi,NaN
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung,NaN
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple,NaN
8,Petrov,Nikolay,ВИП,4810,72,88,7188,Moscow,Apple,NaN
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple,NaN
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi,NaN
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung,NaN
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple,NaN
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi,NaN
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei,NaN
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple,NaN
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi,NaN
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei,NaN
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple,NaN
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung,NaN
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi,NaN
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi,NaN
22,Girev,Sergey,Все за 300,4230,62,68,5512,Kazan,Samsung,NaN
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi,NaN
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple,NaN
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei,NaN
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei,NaN
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi,NaN
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi,NaN
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung,NaN

### Задача 6
Измените название колонки balance на client_balance:
![Картинка испарилась(((](https://ucarecdn.com/b9c0bc93-6525-4af6-963e-7fd389d58750/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [144]:
df6 = df

In [145]:
df6.rename(columns={'balance': "client_balance"}, inplace=True)
df6

,surname,name,tarif,client_balance,age,sms,voice,city,phone
0,Girev,Andrey,ВИП,2757,29,58,6358,Moscow,Xiaomi
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung
2,Ivanov,Alex,Всё за 800,410,47,81,3582,Moscow,Huawei
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple
8,Petrov,Nikolay,ВИП,4722,72,88,7188,Moscow,Apple
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung

In [ ]:
#Еще способы решения 
df6.columns.values[3] = 'client_balance'
df6.columns = df6.columns.str.replace('balance','client_balance')

### Задача 7
Пересчитайте баланс пользователей в доллары по курсу 1 доллар = 60 рублей. Результат запишите в колонку balance_usd (ответ округлите до двух знаков после запятой). Исходный баланс лежит в столбце balance:
![Картинка испарилась(((](https://ucarecdn.com/7ab6f518-a5b8-428e-a265-5d26740d80aa/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [23]:
df7 = df

In [24]:
df7['balance_usd'] = round(df7['balance'] / 60,2)
df7

,surname,name,tarif,balance,age,sms,voice,city,phone,balance_usd
0,Girev,Andrey,ВИП,2815,29,58,6358,Moscow,Xiaomi,46.92
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,60.57
2,Ivanov,Alex,Всё за 800,410,47,81,3582,Moscow,Huawei,6.83
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple,33.02
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung,82.82
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi,71.80
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung,5.00
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple,69.98
8,Petrov,Nikolay,ВИП,4810,72,88,7188,Moscow,Apple,80.17
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple,68.63
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi,33.18
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung,23.83
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple,1.88
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi,56.57
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei,58.22
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple,76.08
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi,53.20
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei,62.73
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple,63.60
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung,13.62
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi,6.42
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi,44.03
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung,70.50
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi,68.33
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple,56.18
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei,59.62
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei,45.70
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi,44.07
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi,78.75
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung,46.42

### Задача 8
Высшее руководство компании в ячейке с балансом (в долларах) хотят видеть знак доллара $. Вам как самому ответственному и подготовленному специалисту доверили довести дело до конца! Добавьте, пожалуйста, знак доллара)
![Картинка испарилась(((](https://ucarecdn.com/474c4257-4854-45ee-9196-5f7ed48f53c8/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [25]:
df7['balance_usd'] = df7['balance_usd'].astype('str') + ' $'

In [26]:
df7

,surname,name,tarif,balance,age,sms,voice,city,phone,balance_usd
0,Girev,Andrey,ВИП,2815,29,58,6358,Moscow,Xiaomi,46.92 $
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,60.57 $
2,Ivanov,Alex,Всё за 800,410,47,81,3582,Moscow,Huawei,6.83 $
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple,33.02 $
4,Girev,Stas,Всё за 800,4969,43,61,8510,Moscow,Samsung,82.82 $
5,Bykin,Andrey,Всё за 500,4308,49,39,2525,Moscow,Xiaomi,71.8 $
6,Kozlov,Igor,Всё за 800,300,60,31,8543,Yakutsk,Samsung,5.0 $
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple,69.98 $
8,Petrov,Nikolay,ВИП,4810,72,88,7188,Moscow,Apple,80.17 $
9,Andreev,Sergey,Всё за 800,4118,52,53,419,Yakutsk,Apple,68.63 $
10,Smolov,Stas,Промо,1991,28,67,5016,Kazan,Xiaomi,33.18 $
11,Girev,Igor,Корпоративный,1430,69,19,9520,Yakutsk,Samsung,23.83 $
12,Kozlov,Andrey,Корпоративный,113,71,82,2785,Kazan,Apple,1.88 $
13,Ivanov,Sergey,Промо,3394,39,12,2718,Yakutsk,Xiaomi,56.57 $
14,Smolov,Sergey,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei,58.22 $
15,Kozlov,Stas,Всё за 800,4565,59,82,3168,Moscow,Apple,76.08 $
16,Vlasov,Andrey,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi,53.2 $
17,Smolov,Alex,Корпоративный,3764,71,22,2768,Moscow,Huawei,62.73 $
18,Vlasov,Sergey,Всё за 800,3816,28,35,5734,Vladivostok,Apple,63.6 $
19,Bykin,Alex,Промо,817,65,34,2131,Vladivostok,Samsung,13.62 $
20,Andreev,Nikolay,Всё за 500,385,49,62,1815,Kazan,Xiaomi,6.42 $
21,Bykin,Igor,Всё за 500,2642,38,11,3787,Moscow,Xiaomi,44.03 $
22,Girev,Sergey,Все за 300,4230,62,68,5512,Vladivostok,Samsung,70.5 $
23,Bykin,Sergey,Всё за 800,4100,48,39,227,Moscow,Xiaomi,68.33 $
24,Girev,Stas,Все за 300,3371,53,24,7946,Kazan,Apple,56.18 $
25,Smolov,Sergey,Корпоративный,3577,70,71,8847,Yakutsk,Huawei,59.62 $
26,Mezov,Nikolay,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei,45.7 $
27,Smolov,Stas,Всё за 500,2644,41,33,8341,Moscow,Xiaomi,44.07 $
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi,78.75 $
29,Ivanov,Nikolay,Всё за 500,2785,41,5,2901,Moscow,Samsung,46.42 $

### Задача 9
Расcчитайте долю смс для каждого пользователя. Для этого определите сколько всего было отправлено СМС, а затем расcчитайте отношение отправленных смс клиента к общему количеству. Столбец назовите sms_volume. Оставьте TOP-3:
![Картинка испарилась(((](https://ucarecdn.com/8536499a-521b-4882-b173-6832b25084a5/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [45]:
df['sms_volume'] = df['sms']/df['sms'].sum()
df = df.sort_values(by='sms_volume',ascending=False)[:3]

In [47]:
df

,surname,name,tarif,balance,age,sms,voice,city,phone,sms_volume
3,Andreev,Sergey,Всё за 500,1981,75,98,5442,Kazan,Apple,0.063844
28,Vlasov,Andrey,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi,0.060586
7,Girev,Alex,Промо,4199,47,90,3925,Kazan,Apple,0.058632

### Задача 10
Cредний возраст клиентов из Казани выше чем во Владивостоке? Функция должна вернуть True - если да и False - если нет.

In [61]:
df.groupby(['city']).mean()

                 balance        age        sms        voice
city
Kazan        2239.142857  51.428571  71.571429  3933.000000
Moscow       3437.454545  48.909091  47.181818  4486.818182
Vladivostok  3397.000000  45.250000  57.500000  5704.500000
Yakutsk      2780.750000  47.375000  35.625000  6121.625000

In [54]:
df_kaz=df[df['city'] == 'Kazan']
df_kaz

    surname     name          tarif  balance  age  sms  voice   city    phone
1     Bykin     Stas     Все за 300     3634   37   78    602  Kazan  Samsung
3   Andreev   Sergey     Всё за 500     1981   75   98   5442  Kazan    Apple
7     Girev     Alex          Промо     4199   47   90   3925  Kazan    Apple
10   Smolov     Stas          Промо     1991   28   67   5016  Kazan   Xiaomi
12   Kozlov   Andrey  Корпоративный      113   71   82   2785  Kazan    Apple
20  Andreev  Nikolay     Всё за 500      385   49   62   1815  Kazan   Xiaomi
24    Girev     Stas     Все за 300     3371   53   24   7946  Kazan    Apple

In [55]:
df_vl=df[df['city'] == 'Vladivostok']
df_vl

   surname    name       tarif  balance  age  sms  voice         city    phone
18  Vlasov  Sergey  Всё за 800     3816   28   35   5734  Vladivostok    Apple
19   Bykin    Alex       Промо      817   65   34   2131  Vladivostok  Samsung
22   Girev  Sergey  Все за 300     4230   62   68   5512  Vladivostok  Samsung
28  Vlasov  Andrey  Всё за 500     4725   26   93   9441  Vladivostok   Xiaomi

In [57]:
df_kaz['age'].mean() > df_vl['age'].mean()

True

In [ ]:
#Итоговый вариант решения
import pandas as pd

def solution(df):
    df_kaz=df[df['city'] == 'Kazan']
    df_vl=df[df['city'] == 'Vladivostok']
    return df_kaz['age'].mean() > df_vl['age'].mean()

In [ ]:
#Упрощенный итоговый вариант
import pandas as pd

def solution(df):
    return df[df.city == 'Kazan'].age.mean() > df[df.city == 'Moscow'].age.mean()

### Задача 11
Создайте индекс для строк на основе столбцов surname и name. После создания индекса удалите столбцы surname и name:

![Картинка испарилась(((](https://ucarecdn.com/ee142679-898a-4a99-b075-98c5269368ea/)
(На картинке первые 11 строк финального датафрейма. Вам нужно выполнить действия для каждой строки и вернуть датафрейм полностью)

In [101]:
def solution(df):
    df.index = df['surname'].str.upper() + '_' + df['name'].str.upper()
    del [df['surname'], df['name']]
    return df

In [102]:
solution(df)

,tarif,balance,age,sms,voice,city,phone
GIREV_ANDREY,ВИП,2815,29,58,6358,Moscow,Xiaomi
BYKIN_STAS,Все за 300,3634,37,78,602,Kazan,Samsung
IVANOV_ALEX,Всё за 800,410,47,81,3582,Moscow,Huawei
ANDREEV_SERGEY,Всё за 500,1981,75,98,5442,Kazan,Apple
GIREV_STAS,Всё за 800,4969,43,61,8510,Moscow,Samsung
BYKIN_ANDREY,Всё за 500,4308,49,39,2525,Moscow,Xiaomi
KOZLOV_IGOR,Всё за 800,300,60,31,8543,Yakutsk,Samsung
GIREV_ALEX,Промо,4199,47,90,3925,Kazan,Apple
PETROV_NIKOLAY,ВИП,4810,72,88,7188,Moscow,Apple
ANDREEV_SERGEY,Всё за 800,4118,52,53,419,Yakutsk,Apple
SMOLOV_STAS,Промо,1991,28,67,5016,Kazan,Xiaomi
GIREV_IGOR,Корпоративный,1430,69,19,9520,Yakutsk,Samsung
KOZLOV_ANDREY,Корпоративный,113,71,82,2785,Kazan,Apple
IVANOV_SERGEY,Промо,3394,39,12,2718,Yakutsk,Xiaomi
SMOLOV_SERGEY,Всё за 250 (архив),3493,32,6,8959,Yakutsk,Huawei
KOZLOV_STAS,Всё за 800,4565,59,82,3168,Moscow,Apple
VLASOV_ANDREY,Всё за 800,3192,29,74,2852,Yakutsk,Xiaomi
SMOLOV_ALEX,Корпоративный,3764,71,22,2768,Moscow,Huawei
VLASOV_SERGEY,Всё за 800,3816,28,35,5734,Vladivostok,Apple
BYKIN_ALEX,Промо,817,65,34,2131,Vladivostok,Samsung
ANDREEV_NIKOLAY,Всё за 500,385,49,62,1815,Kazan,Xiaomi
BYKIN_IGOR,Всё за 500,2642,38,11,3787,Moscow,Xiaomi
GIREV_SERGEY,Все за 300,4230,62,68,5512,Vladivostok,Samsung
BYKIN_SERGEY,Всё за 800,4100,48,39,227,Moscow,Xiaomi
GIREV_STAS,Все за 300,3371,53,24,7946,Kazan,Apple
SMOLOV_SERGEY,Корпоративный,3577,70,71,8847,Yakutsk,Huawei
MEZOV_NIKOLAY,Всё за 250 (архив),2742,28,19,7115,Yakutsk,Huawei
SMOLOV_STAS,Всё за 500,2644,41,33,8341,Moscow,Xiaomi
VLASOV_ANDREY,Всё за 500,4725,26,93,9441,Vladivostok,Xiaomi
IVANOV_NIKOLAY,Всё за 500,2785,41,5,2901,Moscow,Samsung

### Задача 12
Являются ли лейблы строк уникальными (не повторяющимися)? Верните True - если уникальные и False - если есть дубли. Пример входящего датафрейма:

![Картинка испарилась(((](https://ucarecdn.com/7e5eb4d9-62d0-488c-acff-f83448b3cd95/)

In [107]:
#Мой топорный вариант решения. Если неуникальны. то количество не совпадет
df12 = df
len(df12.index) == len(df12.index.unique())

False

In [108]:
#И нормальный варианты с помощью метода, который есть в pd
import pandas as pd

def solution(df):
    return df.index.is_unique

In [109]:
solution(df)

False